### ISSUE TITLE
Direct Access

### ISSUE THREAD

**Issue by ahmadko** [TheChoyon/Zone-H-Archive-Grabber#1]
Thank you for your work, I'm trying to build the same and I was wondering why ur reading the info from Google Cache, not directly? is there a way to scrape Zone-H directly?

Thank you.

**Comment by TheChoyon** [comment]
Thank you for your question, I am little bit late to check the issues of repositories actually. Zone-h uses javascript in the homepage. so python normally does not follow redirects using javascript. You can make direct accessible one by using modules like selenium and phantomjs with it.
